name = "next-supabase-saas"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-11-1"

[build]
command = "pnpm build"

[build.upload]
format = "service-worker"

[env.production]
workers_dev = false
route = "your-domain.com/*"

[env.staging]
workers_dev = true

[[kv_namespaces]]
binding = "KV"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

compatibility_flags = [ "nodejs_compat" ]

